### ISSUE TITLE
Implementar identificador para tokens do tipo string constante

### ISSUE THREAD

**Issue by GaibVargas** [GaibVargas/compiladores#14]
É necessário fazer a implementação do identificador de tokens para strings constantes. A implementação deve ser feita nos moldes dos identificadores já existentes, além de adicioná-lo para a lista de identificadores utilizados pelo analisador léxico.

**Comment by Tulio-bardini** [comment]
Mais detalhes em https://github.com/GaibVargas/compiladores/pull/30
