### ISSUE TITLE
Escrever 3 programas com 100 linhas no mínimo

### ISSUE THREAD

**Issue by GaibVargas** [GaibVargas/compiladores#21]
Essa é uma obrigação para a entrega do trabalho, com risco de nota zero caso não seja cumprida. É necessário escrever 3 programas que não contenham erros léxicos, sintáticos e nem semânticos além de possuírem no mínimo 100 linhas cada um.

**Comment by Tulio-bardini** [comment]
Mais detalhes em https://github.com/GaibVargas/compiladores/pull/32
